export const parameterDefaults = {
    palette: ['#1a1a2e', '#16213e', '#0f3460', '#533483', '#e94560'],
    energy: 0.5,
    complexity: 0.5,
    organicness: 0.7,
    density: 0.5,
    mood: 'serene',
    elements: ['particles', 'fog'],
    shapes: ['blobs'],
    movement: 'floating',
    depth: 0.6,
    glow: 0.5,
    noiseScale: 0.3,
    contrast: 0.5,
    temperature: 0.5,
};

// Presets for quick access
export const presets = {
    'cosmic loneliness': {
        palette: ['#0a0a14', '#1a1a2e', '#2d1b4e', '#4a2c6f', '#8b5cf6'],
        energy: 0.2,
        complexity: 0.6,
        organicness: 0.8,
        density: 0.3,
        mood: 'mysterious',
        elements: ['particles', 'fog', 'blobs'],
        shapes: ['spheres'],
        movement: 'floating',
        depth: 0.9,
        glow: 0.7,
        noiseScale: 0.2,
        contrast: 0.3,
        temperature: 0.2,
    },
    'warm anxiety': {
        palette: ['#331a00', '#663300', '#cc6600', '#ff8c00', '#ffa500'],
        energy: 0.7,
        complexity: 0.6,
        organicness: 0.5,
        density: 0.6,
        mood: 'anxious',
        elements: ['particles', 'flow_field'],
        shapes: ['streaks'],
        movement: 'pulsing',
        depth: 0.5,
        glow: 0.6,
        noiseScale: 0.5,
        contrast: 0.6,
        temperature: 0.9,
    },
    'underwater cathedral': {
        palette: ['#001a1a', '#003333', '#004d4d', '#006666', '#008080'],
        energy: 0.3,
        complexity: 0.8,
        organicness: 0.9,
        density: 0.4,
        mood: 'dreamy',
        elements: ['particles', 'fog', 'ribbons'],
        shapes: ['droplets', 'ripples'],
        movement: 'floating',
        depth: 0.8,
        glow: 0.4,
        noiseScale: 0.3,
        contrast: 0.4,
        temperature: 0.3,
    },
    'melancholy neon rain': {
        palette: ['#1a1a2e', '#16213e', '#0f3460', '#e94560', '#ff6b9d'],
        energy: 0.4,
        complexity: 0.7,
        organicness: 0.6,
        density: 0.5,
        mood: 'melancholy',
        elements: ['particles', 'flow_field', 'fog'],
        shapes: ['droplets', 'streaks'],
        movement: 'falling',
        depth: 0.7,
        glow: 0.6,
        noiseScale: 0.4,
        contrast: 0.65,
        temperature: 0.4,
    },
};
